name: Release Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          ext=""
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            ext=".exe"
          fi
          mkdir -p dist
          cp target/${{ matrix.target }}/release/nrs dist/nrs-${{ matrix.target }}$ext

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/nrs-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

